CREATE TABLE TOURNAMENT (
					Id INT IDENTITY(1,1) NOT NULL,
					CodeTournament AS ('TR'+ RIGHT('00000'+CONVERT(VARCHAR, Id),(4))) PERSISTED NOT NULL,
					[Name] VARCHAR(30) NOT NULL,
					StartDate DATE NOT NULL,
					EndDate DATE NOT NULL,
					Rules VARCHAR(1000),
					[Type] VARCHAR (50)

);
CREATE TABLE STAGE(
					Id INT IDENTITY(1,1) NOT NULL,
					[Name] VARCHAR (30) NOT NULL,
					Torneo_ID VARCHAR (6) NOT NULL
);
CREATE TABLE [MATCH](
					Id INT IDENTITY(1,1) NOT NULL,
					Stadium VARCHAR (50) NOT NULL,
					Team1 VARCHAR (50) NOT NULL,
					Team2 VARCHAR (50) NOT NULL,
					StartDateTime DATE NOT NULL, 
					Torneo_ID VARCHAR(6) NOT NULL,
					Fase_ID INT NOT NULL,
					[State] VARCHAR(5) NOT NULL,
					score VARCHAR (10) NOT NULL
);

ALTER TABLE TOURNAMENT
ADD CONSTRAINT IDTORNEO_PK PRIMARY KEY(CodeTournament);

ALTER TABLE STAGE
ADD CONSTRAINT IDFASE_TORNEO_FK FOREIGN KEY (Torneo_ID)
REFERENCES TOURNAMENT(CodeTournament),
CONSTRAINT IDFASE_PK PRIMARY KEY (Id);

ALTER TABLE [MATCH]
ADD CONSTRAINT IDPARTIDO_TORNEO_FK FOREIGN KEY (Torneo_ID)
REFERENCES TOURNAMENT(CodeTournament),
CONSTRAINT IDPARTIDO_FASE_FK FOREIGN KEY (Fase_ID)
REFERENCES STAGE(Id),
CONSTRAINT IDPARTIDO_PK PRIMARY KEY (Id,Fase_ID,Torneo_ID);

INSERT INTO TOURNAMENT VALUES('HOLA', '12-03-09', '10-12-20','JIHIE','DJWNEII')
SELECT * FROM TOURNAMENT

