CREATE TABLE TORNEO (
					Id VARCHAR(6) NOT NULL,
					Nombre VARCHAR(30) NOT NULL,
					Fecha_inicio DATE NOT NULL,
					Fecha_final DATE NOT NULL,
					Descripción VARCHAR(1000),
					Tipo VARCHAR (50)

);
CREATE TABLE FASE(
					Id VARCHAR (6) NOT NULL,
					Nombre VARCHAR (30) NOT NULL,
					Fecha_inicio DATE NOT NULL,
					Fecha_final DATE NOT NULL,
					Torneo_ID VARCHAR(6) NOT NULL
);
CREATE TABLE PARTIDO(
					Id INT IDENTITY(1,1) NOT NULL,
					Estadio VARCHAR (50) NOT NULL,
					Equipo_1 VARCHAR (50) NOT NULL,
					Equipo_2 VARCHAR (50) NOT NULL,
					Fecha_ini DATE NOT NULL, 
					Torneo_ID VARCHAR(6) NOT NULL,
					Fase_ID VARCHAR(6) NOT NULL
);

ALTER TABLE TORNEO
ADD CONSTRAINT IDTORNEO_PK PRIMARY KEY(Id);

ALTER TABLE FASE
ADD CONSTRAINT IDFASE_TORNEO_FK FOREIGN KEY (Torneo_ID)
REFERENCES TORNEO(Id),
CONSTRAINT IDFASE_PK PRIMARY KEY (Id);

ALTER TABLE PARTIDO
ADD CONSTRAINT IDPARTIDO_TORNEO_FK FOREIGN KEY (Torneo_ID)
REFERENCES TORNEO(Id),
CONSTRAINT IDPARTIDO_FASE_FK FOREIGN KEY (Fase_ID)
REFERENCES FASE(Id),
CONSTRAINT IDPARTIDO_PK PRIMARY KEY (Id,Fase_ID,Torneo_ID);

