CREATE TABLE TOURNAMENT (
					Id INT IDENTITY(1,1) NOT NULL,
					CodeTournament AS ('TR'+ RIGHT('00000'+CONVERT(VARCHAR, Id),(4))) PERSISTED NOT NULL,
					[Name] VARCHAR(30) NOT NULL,
					StartDate DATE NOT NULL,
					EndDate DATE NOT NULL,
					Rules VARCHAR(1000),
					[Type] VARCHAR (50)

);
CREATE TABLE STAGE(
					Id INT IDENTITY(1,1) NOT NULL,
					[Name] VARCHAR (30) NOT NULL,
					Tournament_ID VARCHAR (6) NOT NULL
);
CREATE TABLE [MATCH](
					Id INT IDENTITY(1,1) NOT NULL,
					Stadium VARCHAR (50) NOT NULL,
					StartDateTime DATETIME NOT NULL, 
					Tournament_ID VARCHAR(6) NOT NULL,
					Stage_ID INT NOT NULL,
					[State] VARCHAR(20) NOT NULL,
					Score VARCHAR (10) NOT NULL
);
CREATE TABLE TEAM(
				Id INT IDENTITY(1,1) NOT NULL,
				[Name] VARCHAR(100) NOT NULL,
				[Type] VARCHAR(50) NOT NULL
);
CREATE TABLE PLAYER(
				Id INT IDENTITY(1,1) NOT NULL,
				[Name] VARCHAR(50) NOT NULL,
				BirthDate DATE NOT NULL,
				Age INT NOT NULL,
				Rol VARCHAR(50) NOT NULL
);
CREATE TABLE TEAM_MATCH(
						Id_Team INT NOT NULL,
						Id_Match INT NOT NULL
);
CREATE TABLE PLAYER_TEAM(
						Id_Team INT NOT NULL,
						Id_Player INT NOT NULL
);
CREATE TABLE COMPETE(
					Id_Team INT NOT NULL,
					TournamentCode VARCHAR(6) NOT NULL
);

ALTER TABLE TOURNAMENT
ADD CONSTRAINT IDTORNEO_PK PRIMARY KEY(CodeTournament);

ALTER TABLE STAGE
ADD CONSTRAINT IDFASE_TORNEO_FK FOREIGN KEY (Tournament_ID)
REFERENCES TOURNAMENT(CodeTournament),
CONSTRAINT IDFASE_PK PRIMARY KEY (Id);

ALTER TABLE [MATCH]
ADD CONSTRAINT IDPARTIDO_TORNEO_FK FOREIGN KEY (Tournament_ID)
REFERENCES TOURNAMENT(CodeTournament),
CONSTRAINT IDPARTIDO_FASE_FK FOREIGN KEY (Stage_ID)
REFERENCES STAGE(Id),
CONSTRAINT IDPARTIDO_PK PRIMARY KEY (Id);

ALTER TABLE TEAM
ADD CONSTRAINT ID_TEAM_PK PRIMARY KEY (Id);

ALTER TABLE PLAYER
ADD CONSTRAINT IDPLAYER_PK PRIMARY KEY (Id);

ALTER TABLE TEAM_MATCH
ADD CONSTRAINT TEAMFK_M FOREIGN KEY (Id_Team)
REFERENCES TEAM(Id),
CONSTRAINT MATCHFK FOREIGN KEY (Id_Match)
REFERENCES [MATCH](Id),
CONSTRAINT TEAM_MATCH_PK PRIMARY KEY (Id_Team, Id_Match);

ALTER TABLE PLAYER_TEAM
ADD CONSTRAINT TEAMFK_P_T FOREIGN KEY (Id_Team)
REFERENCES TEAM(Id),
CONSTRAINT PLAYERFK FOREIGN KEY (Id_Player)
REFERENCES PLAYER(Id),
CONSTRAINT PLAYER_TEAM_PK PRIMARY KEY (Id_Team, Id_Player);

ALTER TABLE COMPETE
ADD CONSTRAINT TEAMFK_C FOREIGN KEY (Id_Team)
REFERENCES TEAM(Id),
CONSTRAINT TOURNFK FOREIGN KEY (TournamentCode)
REFERENCES TOURNAMENT(CodeTournament),
CONSTRAINT COMPETEPK PRIMARY KEY (Id_Team, TournamentCode);